version: '3.8'

services:
  gradio:
    image: gradio-demo:latest
    build:
      context: .
      dockerfile: .docker/gradio/Dockerfile
    ports:
      - "7860:7860"
    environment:
      - PYTHONPATH=/app